# Generated by Django 3.0.5 on 2020-09-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200915_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.TextField(blank='123'),
        ),
    ]
